[tool.poetry]
name = "homeworkweb4"
version = "0.1.0"
description = ""
authors = ["Oleksandr Study"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
jinja2 = "^3.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
